<?php

return [
    'permissions' => [
        'organization.view', 'organization.update', 'organization.create',
        'organization.suspend', 'organization.reactivate',
        'users.view', 'users.create', 'users.update', 'users.delete', 'users.invite',
        'roles.view', 'roles.create', 'roles.update', 'roles.delete',
        'permissions.view', 'permissions.assign', 'audit.view',
        'learners.view', 'learners.create', 'learners.update', 'learners.archive',
        'learners.restore', 'learners.export',
        'group.view', 'group.create', 'group.update', 'group.archive',
        'group.restore', 'group.learners.manage',
        'schedule.view', 'schedule.create', 'schedule.update', 'schedule.cancel',
        'attendance.view', 'attendance.take', 'attendance.validate',
        'attendance.correct', 'attendance.view_reports',
        'placement_questions.view', 'placement_questions.create',
        'placement_questions.update', 'placement_questions.disable',
        'placement_tests.view', 'placement_tests.start', 'placement_tests.complete',
        'placement_tests.review', 'learner_levels.view', 'learner_levels.update',
    ],
    'roles' => [
        'Organization Admin' => ['*'],
        'Manager' => [
            'organization.view', 'organization.update', 'users.view', 'users.create',
            'users.update', 'users.invite', 'roles.view', 'permissions.view',
            'learners.view', 'learners.create', 'learners.update', 'learners.archive',
            'learners.restore', 'learners.export',
            'group.view', 'group.create', 'group.update', 'group.archive',
            'group.restore', 'group.learners.manage',
            'schedule.view', 'schedule.create', 'schedule.update', 'schedule.cancel',
            'attendance.view', 'attendance.take', 'attendance.validate',
            'attendance.correct', 'attendance.view_reports',
            'placement_questions.view', 'placement_questions.create',
            'placement_questions.update', 'placement_questions.disable',
            'placement_tests.view', 'placement_tests.start', 'placement_tests.complete',
            'placement_tests.review', 'learner_levels.view', 'learner_levels.update',
        ],
        'Teacher/Trainer' => [
            'organization.view', 'users.view', 'group.view', 'schedule.view',
            'attendance.view', 'attendance.take', 'attendance.validate',
            'placement_questions.view', 'placement_tests.view',
            'learner_levels.view', 'learner_levels.update',
        ],
        'Accountant' => [
            'organization.view', 'users.view', 'learners.view', 'learners.create',
            'learners.update', 'learners.archive', 'learners.export',
        ],
        'Staff' => [
            'organization.view', 'learners.view', 'learners.create', 'learners.update',
            'learners.archive', 'learners.export',
            'group.view', 'group.create', 'group.update', 'group.archive',
            'group.restore', 'group.learners.manage',
            'schedule.view', 'schedule.create', 'schedule.update', 'schedule.cancel',
            'attendance.view', 'attendance.take', 'attendance.validate',
            'attendance.correct', 'attendance.view_reports',
            'placement_questions.view', 'placement_tests.view',
            'placement_tests.start', 'placement_tests.complete', 'learner_levels.view',
        ],
    ],
];
